//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by Unity Input System.
//     如果 Unity 自动生成了此类，请删除本文件，使用自动生成的版本。
//     如果项目还没装 Input System，可先使用此类作为临时方案。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Controls;

/// <summary>
/// 玩家输入动作映射
/// 由 Unity Input System 的 .inputactions 文件生成
/// </summary>
public partial class PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
            ""name"": ""PlayerInputActions"",
            ""maps"": [
                {
                    ""name"": ""Player"",
                    ""id"": ""a1b2c3d4-e5f6-7890-abcd-ef1234567890"",
                    ""actions"": [
                        {
                            ""name"": ""Move"",
                            ""type"": ""Value"",
                            ""id"": ""move-action-id"",
                            ""expectedControlType"": ""Vector2"",
                            ""processors"": """",
                            ""interactions"": """"
                        },
                        {
                            ""name"": ""Run"",
                            ""type"": ""Button"",
                            ""id"": ""run-action-id"",
                            ""expectedControlType"": ""Button"",
                            ""processors"": """",
                            ""interactions"": """"
                        },
                        {
                            ""name"": ""Interact"",
                            ""type"": ""Button"",
                            ""id"": ""interact-action-id"",
                            ""expectedControlType"": ""Button"",
                            ""processors"": """",
                            ""interactions"": """"
                        },
                        {
                            ""name"": ""OpenMap"",
                            ""type"": ""Button"",
                            ""id"": ""openmap-action-id"",
                            ""expectedControlType"": ""Button"",
                            ""processors"": """",
                            ""interactions"": """"
                        },
                        {
                            ""name"": ""Inventory"",
                            ""type"": ""Button"",
                            ""id"": ""inventory-action-id"",
                            ""expectedControlType"": ""Button"",
                            ""processors"": """",
                            ""interactions"": """"
                        },
                        {
                            ""name"": ""Menu"",
                            ""type"": ""Button"",
                            ""id"": ""menu-action-id"",
                            ""expectedControlType"": ""Button"",
                            ""processors"": """",
                            ""interactions"": """"
                        }
                    ],
                    ""bindings"": [
                        {
                            ""name"": ""WASD"",
                            ""id"": ""wasd-binding-id"",
                            ""path"": ""2DVector"",
                            ""interactions"": """",
                            ""processors"": """",
                            ""groups"": ""Keyboard"",
                            ""action"": ""Move"",
                            ""isComposite"": true,
                            ""isPartOfComposite"": false
                        },
                        {
                            ""name"": ""up"",
                            ""id"": ""wasd-up-id"",
                            ""path"": ""<Keyboard>/w"",
                            ""interactions"": """",
                            ""processors"": """",
                            ""groups"": ""Keyboard"",
                            ""action"": ""Move"",
                            ""isComposite"": false,
                            ""isPartOfComposite"": true
                        },
                        {
                            ""name"": ""down"",
                            ""id"": ""wasd-down-id"",
                            ""path"": ""<Keyboard>/s"",
                            ""interactions"": """",
                            ""processors"": """",
                            ""groups"": ""Keyboard"",
                            ""action"": ""Move"",
                            ""isComposite"": false,
                            ""isPartOfComposite"": true
                        },
                        {
                            ""name"": ""left"",
                            ""id"": ""wasd-left-id"",
                            ""path"": ""<Keyboard>/a"",
                            ""interactions"": """",
                            ""processors"": """",
                            ""groups"": ""Keyboard"",
                            ""action"": ""Move"",
                            ""isComposite"": false,
                            ""isPartOfComposite"": true
                        },
                        {
                            ""name"": ""right"",
                            ""id"": ""wasd-right-id"",
                            ""path"": ""<Keyboard>/d"",
                            ""interactions"": """",
                            ""processors"": """",
                            ""groups"": ""Keyboard"",
                            ""action"": ""Move"",
                            ""isComposite"": false,
                            ""isPartOfComposite"": true
                        },
                        {
                            ""name"": ""Arrows"",
                            ""id"": ""arrows-binding-id"",
                            ""path"": ""2DVector"",
                            ""interactions"": """",
                            ""processors"": """",
                            ""groups"": ""Keyboard"",
                            ""action"": ""Move"",
                            ""isComposite"": true,
                            ""isPartOfComposite"": false
                        },
                        {
                            ""name"": ""up"",
                            ""id"": ""arrows-up-id"",
                            ""path"": ""<Keyboard>/upArrow"",
                            ""interactions"": """",
                            ""processors"": """",
                            ""groups"": ""Keyboard"",
                            ""action"": ""Move"",
                            ""isComposite"": false,
                            ""isPartOfComposite"": true
                        },
                        {
                            ""name"": ""down"",
                            ""id"": ""arrows-down-id"",
                            ""path"": ""<Keyboard>/downArrow"",
                            ""interactions"": """",
                            ""processors"": """",
                            ""groups"": ""Keyboard"",
                            ""action"": ""Move"",
                            ""isComposite"": false,
                            ""isPartOfComposite"": true
                        },
                        {
                            ""name"": ""left"",
                            ""id"": ""arrows-left-id"",
                            ""path"": ""<Keyboard>/leftArrow"",
                            ""interactions"": """",
                            ""processors"": """",
                            ""groups"": ""Keyboard"",
                            ""action"": ""Move"",
                            ""isComposite"": false,
                            ""isPartOfComposite"": true
                        },
                        {
                            ""name"": ""right"",
                            ""id"": ""arrows-right-id"",
                            ""path"": ""<Keyboard>/rightArrow"",
                            ""interactions"": """",
                            ""processors"": """",
                            ""groups"": ""Keyboard"",
                            ""action"": ""Move"",
                            ""isComposite"": false,
                            ""isPartOfComposite"": true
                        },
                        {
                            ""name"": """",
                            ""id"": ""gamepad-move-id"",
                            ""path"": ""<Gamepad>/leftStick"",
                            ""interactions"": """",
                            ""processors"": """",
                            ""groups"": ""Gamepad"",
                            ""action"": ""Move"",
                            ""isComposite"": false,
                            ""isPartOfComposite"": false
                        },
                        {
                            ""name"": """",
                            ""id"": ""run-keyboard-id"",
                            ""path"": ""<Keyboard>/shift"",
                            ""interactions"": """",
                            ""processors"": """",
                            ""groups"": ""Keyboard"",
                            ""action"": ""Run"",
                            ""isComposite"": false,
                            ""isPartOfComposite"": false
                        },
                        {
                            ""name"": """",
                            ""id"": ""run-gamepad-id"",
                            ""path"": ""<Gamepad>/leftTrigger"",
                            ""interactions"": """",
                            ""processors"": """",
                            ""groups"": ""Gamepad"",
                            ""action"": ""Run"",
                            ""isComposite"": false,
                            ""isPartOfComposite"": false
                        },
                        {
                            ""name"": """",
                            ""id"": ""interact-keyboard-id"",
                            ""path"": ""<Keyboard>/f"",
                            ""interactions"": """",
                            ""processors"": """",
                            ""groups"": ""Keyboard"",
                            ""action"": ""Interact"",
                            ""isComposite"": false,
                            ""isPartOfComposite"": false
                        },
                        {
                            ""name"": """",
                            ""id"": ""openmap-keyboard-id"",
                            ""path"": ""<Keyboard>/m"",
                            ""interactions"": """",
                            ""processors"": """",
                            ""groups"": ""Keyboard"",
                            ""action"": ""OpenMap"",
                            ""isComposite"": false,
                            ""isPartOfComposite"": false
                        },
                        {
                            ""name"": """",
                            ""id"": ""inventory-keyboard-id"",
                            ""path"": ""<Keyboard>/e"",
                            ""interactions"": """",
                            ""processors"": """",
                            ""groups"": ""Keyboard"",
                            ""action"": ""Inventory"",
                            ""isComposite"": false,
                            ""isPartOfComposite"": false
                        },
                        {
                            ""name"": """",
                            ""id"": ""menu-keyboard-id"",
                            ""path"": ""<Keyboard>/escape"",
                            ""interactions"": """",
                            ""processors"": """",
                            ""groups"": ""Keyboard"",
                            ""action"": ""Menu"",
                            ""isComposite"": false,
                            ""isPartOfComposite"": false
                        }
                    ]
                }
            ],
            ""controlSchemes"": [
                {
                    ""name"": ""Keyboard"",
                    ""bindingGroup"": ""Keyboard"",
                    ""devices"": [
                        {
                            ""devicePath"": ""<Keyboard>"",
                            ""isOptional"": false,
                            ""isOR"": false
                        }
                    ]
                },
                {
                    ""name"": ""Gamepad"",
                    ""bindingGroup"": ""Gamepad"",
                    ""devices"": [
                        {
                            ""devicePath"": ""<Gamepad>"",
                            ""isOptional"": true,
                            ""isOR"": false
                        }
                    ]
                }
            ]
        }");

        // Player action map
        var playerMap = asset.FindActionMap("Player");
        Move = playerMap?.FindAction("Move");
        Run = playerMap?.FindAction("Run");
        Interact = playerMap?.FindAction("Interact");
        OpenMap = playerMap?.FindAction("OpenMap");
        Inventory = playerMap?.FindAction("Inventory");
        Menu = playerMap?.FindAction("Menu");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player action map
    public InputAction Move { get; private set; }
    public InputAction Run { get; private set; }
    public InputAction Interact { get; private set; }
    public InputAction OpenMap { get; private set; }
    public InputAction Inventory { get; private set; }
    public InputAction Menu { get; private set; }

    public InputActionMap Player => asset.FindActionMap("Player");
}
